### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by andyw8** [financeit/marqeta#53]
@frbk I'd like to enable CI for this repo, so it probably makes sense to use GitLab. What's the first step?

**Comment by frbk** [comment]
Gitlab has amazing documentation: https://docs.gitlab.com/ee/ci/yaml/
We are using k8s so you would start off with something like that:
```
stages:
  - test

variables:
  GIT_DEPTH: 1
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test:
  image: $CI_REGISTRY_IMAGE/base:beta (let me know what you need for the base)
  stage: test
  script:
    - bundle install
    - <some other task>
  artifacts: 
   - logs
  tags:
    - cluster
```
We can schedule a meeting if you need more info about this.
